changelog_data = [
    {
        "version": "v1.3.0",
        "date": "March 14, 2026",
        "type": "feature",
        "title": "Site Overhaul + New Navigation",
        "changes": [
            "Channel management view now shows thumbnails, subscriber counts, video counts, and live status at a glance",
            "New channel detail page — full stats, recent stream sessions, bot settings, and owner info in one place",
            "Live status check per channel — hits the YouTube API and shows if they're broadcasting, the stream title, and concurrent viewer count",
            "Overview dashboard now shows a 'Currently Live' counter, 'New Users (7d)', and a recent streams table",
            "Completely redesigned public nav — Features / Blog / About / Status for logged-out users, Blog link added for logged-in users",
            "Mobile hamburger menu on the nav (pure CSS/JS, no extra libraries)",
            "Active page gets an underline indicator in the nav",
            "New /changelog page with the full version history",
            "Homepage 'What's New' banner in the hero section linking to the changelog",
            "Discord community section added to the homepage",
            "Footer now links to Changelog in the Resources section",
            "Site settings: toggle beta banner, post announcements, enable maintenance mode, inject custom CSS — all without touching code",
        ],
        "description": "Big overhaul session. Channel visibility is way better — you can now actually see what's going on across all channels without digging through the database. The navigation has been rebuilt from scratch, and there are new tools behind the scenes for managing the platform.",
    },
    {
        "version": "v1.2.1",
        "date": "March 12, 2026",
        "type": "improvement",
        "title": "Design Overhaul — Less Robotic",
        "changes": [
            "Every page had the same gradient hero and identical card layout — that's been broken up",
            "About page has a dark solid header with left-aligned text now instead of the purple gradient",
            "FAQ hero is shorter and more compact",
            "Contact page drops the hero entirely and just starts with the form",
            "Feature cards on the homepage now have different accent colors per card (indigo, emerald, amber, sky, violet, rose)",
            "Hover effects vary per card — some lift, some glow, some just change border",
            "The 'Setup takes 5 minutes' section is now a horizontal timeline instead of identical cards",
            "Footer: dropped 'All rights reserved', added 'Built by a solo dev' with a link to the blog",
            "New blog post: Making the Site Feel Less Robotic",
        ],
        "description": "I noticed the site looked like every page was generated from the same template — because it basically was. Spent a day breaking the patterns. The pages still share most of the same CSS, I just vary how it's applied.",
    },
    {
        "version": "v1.2.0",
        "date": "March 9, 2026",
        "type": "feature",
        "title": "Platform Tools + Discord Bot Improvements",
        "changes": [
            "Full platform management tools — user management, blog CRUD, contact messages, site settings, analytics",
            "Blog posts can now be created, edited, published/unpublished, and duplicated without touching the database",
            "Global config model for maintenance mode, banners, registration limits, and custom CSS",
            "Discord bot: 11 new slash commands — /unban, /untimeout, /role, /nick, /lock, /unlock, /poll, /embed, /avatar, /moveall, /banlist",
            "Reaction role bug fix — bot was silently failing when member wasn't in cache, now falls back to direct API fetch",
            "Bot status heartbeat — dashboard shows live ping and whether the bot process is running",
        ],
        "description": "Two things in this release: internal tooling so the platform can actually be managed without querying the database directly, and a batch of improvements to the Discord bot side.",
    },
    {
        "version": "v1.1.5",
        "date": "March 7, 2026",
        "type": "improvement",
        "title": "SEO + Discord Community Launch",
        "changes": [
            "Full Open Graph and Twitter Card meta tags on every public page",
            "JSON-LD structured data on the homepage (SoftwareApplication schema)",
            "/sitemap.xml with all public pages, authenticated pages excluded",
            "/robots.txt with noindex on auth/dashboard routes",
            "Community Discord server launched — discord.gg/mzxHumP5nR",
            "Discord invite link added to footer, settings page, contact page, and community page",
            "Bot dashboard shows per-server connection status with 'Invite Bot' button",
            "OG image switched to the Nexus logo",
        ],
        "description": "Platform is in beta, might as well make it findable. Also opened the Discord server — come hang out if you're using Nexus.",
    },
    {
        "version": "v1.1.0",
        "date": "February 24, 2026",
        "type": "feature",
        "title": "Custom Commands + Cooldowns",
        "changes": [
            "Custom commands are live — create !discord, !socials, whatever you want",
            "Variable substitution in responses: {user}, {channel}, {uptime}, {count}",
            "Per-command cooldowns (global, not per-user for now)",
            "Permission levels: everyone / subscribers only / moderators only",
            "Command templates — 30+ pre-made commands across 7 categories you can apply in one click",
            "Nightbot import: paste your !commands export and they get created automatically",
            "Built-in commands are now fully editable (response, cooldown, permissions)",
            "Command search and filter in channel settings",
        ],
        "description": "Commands were the most-requested feature. The basic stuff (!discord, !socials) works and the template system makes it fast to get set up.",
    },
    {
        "version": "v1.0.5",
        "date": "January 18, 2026",
        "type": "fix",
        "title": "YouTube API Quota + Performance Fixes",
        "changes": [
            "Video sync now uses a 5-minute cooldown to prevent quota burns",
            "Auto-sync channels on a background schedule instead of on every dashboard load",
            "Chat polling interval tuned to stay well under daily quota limits",
            "Channel stats (subscriber count, views, video count) cached in database instead of fetching live",
            "Bot status page shows actual quota usage vs daily limit",
        ],
        "description": "YouTube's API quota is 10,000 units per day and it's easy to blow through. Reworked how sync and polling work so that doesn't happen.",
    },
    {
        "version": "v1.0.0",
        "date": "December 12, 2025",
        "type": "feature",
        "title": "Analytics Dashboard Rebuild",
        "changes": [
            "Threw out the original analytics (was hitting the API on every page load) and rewrote it",
            "Data syncs in the background and is stored in Postgres — dashboard reads from DB",
            "Subscriber growth chart, view count over time, video performance cards",
            "Stream session history — peak viewers, average viewers, duration",
            "Video management page with YouTube-style cards and auto-sync",
            "Switched to Chart.js (tried D3 first, it was overkill)",
        ],
        "description": "First version of analytics was slow and burned quota. This is a full rewrite that's actually usable.",
    },
    {
        "version": "v0.9.0",
        "date": "October 20, 2025",
        "type": "feature",
        "title": "Moderation Filters",
        "changes": [
            "Spam filter — catches repeated characters, repeated words, symbol-heavy messages",
            "Caps filter — flags messages >70% uppercase over 8 characters (threshold configurable)",
            "Link filter — blocks URLs unless sender is mod/sub (configurable)",
            "Blocked words list — per-channel, supports regex patterns",
            "Per-violation timeout durations configurable per channel",
            "Whitelist users who are exempt from all filters",
        ],
        "description": "First feature that made Nexus feel like a real tool. The filters aren't perfect — spam detection is regex-based so there are false positives sometimes — but they handle the common cases well.",
    },
    {
        "version": "v0.8.0",
        "date": "August 15, 2025",
        "type": "improvement",
        "title": "Stable Chat Polling",
        "changes": [
            "Live chat polling reliable enough to use on an actual stream",
            "Bot joins stream, reads messages, responds to !commands within seconds",
            "Polling interval tuned to balance responsiveness vs quota usage",
            "Basic built-in commands: !uptime, !title, !bot",
            "Bot posts as nexusbetabot (dedicated account, not your account)",
        ],
        "description": "Got the core bot loop stable. The early versions would drift out of sync or drop messages — that's fixed now.",
    },
    {
        "version": "v0.5.0",
        "date": "June 1, 2025",
        "type": "improvement",
        "title": "First Prototype",
        "changes": [
            "Google OAuth working — sign in with your Google account",
            "YouTube channel auto-detected and linked on login",
            "Basic live chat reading via YouTube Data API",
            "Flask app with SQLite (later switched to Postgres for production)",
        ],
        "description": "Proof of concept. Everything was held together with print statements but it showed the idea was viable.",
    },
    {
        "version": "v0.1.0",
        "date": "April 10, 2025",
        "type": "improvement",
        "title": "Project Started",
        "changes": [
            "Started reading YouTube Data API and Live Streaming API docs",
            "Set up the Flask project structure",
            "Figured out OAuth scopes and quota limits",
            "Basic API call prototypes",
        ],
        "description": "Mostly just research. The original motivation was wanting a decent YouTube stream tool that wasn't built for Twitch first.",
    },
]
